const levels = [
  { width: 3, height: 3, quads: 3 },
  { width: 3, height: 3, quads: 4 },
  { width: 3, height: 4, quads: 4 },
  { width: 3, height: 4, quads: 5 },
  { width: 4, height: 4, quads: 5 },
  { width: 4, height: 5, quads: 5 },
  { width: 4, height: 5, quads: 6 },
  { width: 5, height: 5, quads: 6 },
  { width: 5, height: 6, quads: 6 },
  { width: 5, height: 6, quads: 7 },
  { width: 6, height: 6, quads: 7 },
  { width: 6, height: 7, quads: 7 },
  { width: 6, height: 7, quads: 8 },
  { width: 7, height: 7, quads: 8 },
  { width: 7, height: 8, quads: 8 },
  { width: 7, height: 8, quads: 9 },
  { width: 8, height: 8, quads: 9 },
  { width: 8, height: 8, quads: 10 },
  { width: 8, height: 8, quads: 11 },
  { width: 8, height: 8, quads: 12 },
];

const levels_OldPack = [
  { width: 3, height: 3, quads: 4 },
  { width: 3, height: 4, quads: 5 },
  { width: 3, height: 5, quads: 6 },
  { width: 4, height: 4, quads: 7 },
  { width: 3, height: 6, quads: 7 },
  { width: 4, height: 5, quads: 8 },
  { width: 3, height: 7, quads: 8 },
  { width: 4, height: 6, quads: 9 },
  { width: 5, height: 5, quads: 9 },
  { width: 4, height: 7, quads: 10 },
  { width: 5, height: 6, quads: 10 },
  { width: 4, height: 8, quads: 10 },
  { width: 5, height: 7, quads: 10 },
  { width: 6, height: 6, quads: 10 },
  { width: 5, height: 8, quads: 10 },
  { width: 6, height: 7, quads: 10 },
  { width: 6, height: 8, quads: 10 },
  { width: 7, height: 7, quads: 10 },
  { width: 7, height: 8, quads: 10 },
  { width: 8, height: 8, quads: 10 },
];

const levels_SmallPack = [
  { width: 3, height: 3, quads: 4 },
  { width: 3, height: 4, quads: 5 },
  { width: 4, height: 4, quads: 5 },
  { width: 4, height: 5, quads: 6 },
  { width: 5, height: 5, quads: 6 },
  { width: 5, height: 6, quads: 7 },
  { width: 6, height: 6, quads: 7 },
  { width: 6, height: 7, quads: 8 },
  { width: 7, height: 7, quads: 8 },
  { width: 7, height: 8, quads: 9 },
  { width: 8, height: 8, quads: 9 },
];

export default levels;
